using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WFAThesisProject.Tests
{
    [TestClass()]
    public class RandomPwdGeneratorTests
    {
        [TestMethod()]
        public void RandomPwdGeneratorTest1()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest2()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest3()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest4()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest5()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest6()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest7()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest8()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest9()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest10()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest11()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest12()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
        [TestMethod()]
        public void RandomPwdGeneratorTest13()
        {
            try
            {
                RandomPwdGenerator ngpwd = new RandomPwdGenerator();
                AnalyzePassword napw = new AnalyzePassword(ngpwd.getRandomPwd());
            }
            catch (ErrorLogPassContent e)
            {
                Assert.Fail("Generated PWD in not acceptable");
            }
            catch (Exception)
            {
                Assert.Fail("Unspecified error happened");
            }
        }
    }
}